### ISSUE TITLE
Reattach to multiple processes

### ISSUE THREAD

**Issue by AlexKeySmith** [erlandranvinge/ReAttach#4]
It would be great to be able to reattach to multiple processes at once.

A use case being debugging a multi tier web app which is spread across different worker processes.

Keep up the great work, it's a incredibly useful plugin!

**Comment by erlandranvinge** [comment]
Hi Alex. Thanks for the kind words. I've been trying to implement this a couple of times, and from a tech standpoint its not really that complicated. However, I've had difficulty integrating this in the VS UI in a satisfying way. One of my main goals with the ReAttach-plugin is to make it look and feel like something that could have shipped with the original product. The problem is that the MenuControl (The UI item used to list reattach targets and attach to them) is very limited. Hopefully, I'll find a way.

**Comment by AlexKey** [comment]
No worries @erlandranvinge it's a tricky UI problem.

Oooo: how about Ctrl+R, Ctrl + A to reattach all in the drop down list?

**Comment by erlandranvinge** [comment]
Yep, that key combo is mandatory, he he. Regarding the UI my most promising idea so far is to allow the user to group and pin targets using a new dialog. This dialog will allow users to pick from previously used targets (and perhaps add new ones with a simple browse dialog). The pinned/grouped targets would end up in a separate section (with a separate set of hotkeys) on the ReAttach menu. They would reorder themselves (within their own section) when they're used similar to the behaviour of todays ordinary ReAttach targets.

**Comment by AlexKey** [comment]
That sounds good, I think "pinning" is a good concept to use that most seasoned VS users will be familiar with. This site is pretty good for discussing UX concepts if you've not come across it before: http://ux.stackexchange.com/

**Comment by erlandranvinge** [comment]
This has been added to the list of future improvements.
