### ISSUE TITLE
IIS Website Name

### ISSUE THREAD

**Issue by SonOfSardaar** [erlandranvinge/ReAttach#9]
When we attach to iis processes, currently all we see is w3wp.exe (User), this is not helpfull when we need to attach to a process with particular website. 
so it will be great to have website name appended to the menu item label.

**Comment by erlandranvinge** [comment]
Agreed, that would certainly be a nice addition! Let's see if I remember correctly here. The problem is that w3wp is a process like any other and thus VS (or the OS for that matter) has no easy way of figuring out what host entries that particular process is binding to. Of course, this can be achieved by using different APIs for different combinations of IIS/OS-versions, which is likely how VS does it. It's not pretty however, and that's why I didn't include it in ReAttach.
